import { CheckCircle2, Send } from "lucide-react"
import { useContactForm } from "@/hooks/useContactForm"
import { useSupportTicketForm } from "@/hooks/useSupportTicketForm"
import SectionTitle, { GradientText } from "./SectionTitle"

type FieldProps = { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean }
function Field({ label, value, onChange, type = "text", required }: FieldProps) { return <label>{label}<input type={type} required={required} value={value} onChange={(event) => onChange(event.target.value)}/></label> }

export function SupportSection() {
  const { form, setForm, status, message, submit } = useSupportTicketForm()
  const set = <K extends keyof typeof form>(key: K) => (value: string) => setForm({ ...form, [key]: value })
  return <section id="soporte" className="section"><div className="container"><SectionTitle eyebrow="Soporte">Ticket de <GradientText>atención.</GradientText></SectionTitle><div className="support-layout"><div><p className="lead">Cuéntanos qué necesitas. Nuestro equipo evaluará tu solicitud y te mantendrá informado.</p><ol className="timeline"><li><b>01</b> Registro y código de seguimiento</li><li><b>02</b> Evaluación y asignación</li><li><b>03</b> Resolución y validación</li></ol></div><form className="form-card" onSubmit={submit}><div className="form-grid"><Field label="Nombre" value={form.name} onChange={set("name")} required/><Field label="Correo" type="email" value={form.email} onChange={set("email")} required/><Field label="Empresa" value={form.company} onChange={set("company")}/><Field label="Teléfono" value={form.phone} onChange={set("phone")}/><label>Tipo<select required value={form.category} onChange={(event) => set("category")(event.target.value)}><option value="">Selecciona</option><option>Problema técnico</option><option>Ayuda con una app</option><option>Solicitud de cambio</option><option>Reportar incidencia</option><option>Consulta general</option></select></label><label>Prioridad<select value={form.priority} onChange={(event) => set("priority")(event.target.value)}><option value="">Selecciona</option><option>Alta</option><option>Media</option><option>Baja</option></select></label><Field label="Producto o servicio" value={form.product} onChange={set("product")}/><Field label="Asunto" value={form.subject} onChange={set("subject")} required/></div><label>Descripción<textarea required value={form.description} onChange={(event) => set("description")(event.target.value)} rows={5}/></label><button className="button button--primary" disabled={status === "loading"}>{status === "loading" ? "Enviando..." : "Registrar ticket"}<Send size={16}/></button>{status === "success" && <p className="form-success"><CheckCircle2 size={17}/> Ticket registrado: <b>{message}</b></p>}{status === "error" && <p className="form-error">{message}</p>}</form></div></div></section>
}

export function ContactSection() {
  const { form, setForm, status, message, submit } = useContactForm()
  const set = <K extends keyof typeof form>(key: K) => (value: string) => setForm({ ...form, [key]: value })
  return <section id="contacto" className="section section--contact"><div className="container contact-layout"><div><SectionTitle eyebrow="Contacto">Hagamos realidad<br/><GradientText>tu próxima idea.</GradientText></SectionTitle><p className="lead">Cuéntanos sobre tu reto. Diseñaremos la solución correcta contigo.</p><p className="contact-data">hola@theseusoft.com<br/>+51 (01) 234-5678<br/>San Isidro, Lima, Perú</p></div><form className="form-card" onSubmit={submit}><Field label="Nombre" value={form.name} onChange={set("name")} required/><Field label="Correo" type="email" value={form.email} onChange={set("email")} required/><Field label="Empresa" value={form.company} onChange={set("company")}/><label>Mensaje<textarea required value={form.message} onChange={(event) => set("message")(event.target.value)} rows={6}/></label><button className="button button--primary" disabled={status === "loading"}>{status === "loading" ? "Enviando..." : "Enviar mensaje"}<Send size={16}/></button>{status === "success" && <p className="form-success"><CheckCircle2 size={17}/>{message}</p>}{status === "error" && <p className="form-error">{message}</p>}</form></div></section>
}
